name: 'product-management-web'
on:
  push:
    branches:
      - main

concurrency:
  group: 'pages'
  cancel-in-progress: false
jobs:
  job:
    name: 'Deploy github pages'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
            persist-credentials: false
      - uses: actions/setup-node@v3
        with:
            node-version: 18
      - run: npm i -g yarn
      - run: yarn install
      - run: yarn build

      - name: Deploy   # 部署
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: static-pages # 部署后提交到的分支
          folder: dist # 这里填打包好的目录名称
          repo-token: ${{ secrets.ACTION_TOKEN }}

